version: 2.0

jobs:
  do_it:
    working_directory: ~/app
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Angular CLI
          command: 'echo n | sudo npm install -g --silent @angular/cli'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: 'npm install'
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - 'node_modules'
      - run:
          name: Build for production
          command: 'npm run build-prod'
      - run:
          name: Delete old application
          command: 'ssh -o StrictHostKeyChecking=no -t external@vps778858.ovh.net ''echo y | rm -r /usr/share/nginx/html/lunchroom'''
      - run:
          name: Copy new files to server
          command: 'scp -r ~/app/dist/* external@vps778858.ovh.net:/usr/share/nginx/html/'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - do_it
    